.gitignore, README.md, README_JCE.md, build.xml
This PR is in prep for the wolfcrypt-jni-1.0.0 release and includes:
1. Adds several items to .gitignore
2. Adds title/vendor/version to build.xml, used to stamp JAR when created
3. Updates README with 1.0.0 notes
=> Prep for wolfCrypt JNI 1.0.0 release

build.xml
...so that Jenkins log parsing doesn't fail the test when finding "WARNING"
=> change "WARNING" to "NOTICE"

jni/jni_md5.c
This change allows for the amount of bytes to be hashed(len) to be greater than offset and still checks that offset won't go out of bounds of array.
=> out of bounds check changed from using len(bytes to be hashes) to bufSz(size of array)

src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
Check if using fips and assertEquals on the proper expected error message.
=> wolfssl-fips throws a different error message. Change expected error message if fips. 

jni/include/com_wolfssl_wolfcrypt_Hmac.h, jni/jni_hmac.c, src/main/java/com/wolfssl/wolfcrypt/Hmac.java, src/main/java/com/wolfssl/wolfcrypt/WolfCrypt.java
**02e8e3e** 
INLINE changed to WC_INLINE to match that of wolfssl.  Fixes compile time error.
**64b8e3a** 
6 JNI methods were created:  getCodeSHA, getCodeMd5, etc.
1 java method was created: getHashCode(hashType hash)
The getHashCode accepts an enum argument of hashType such as SHA or MD5.  Depending on the passed in enum; getHashCode will call the respective JNI method such as getCodeSHA.
The JNI method than returns the hash code defined by wolfssl header files.
This allows for different versions of wolfssl to be used without having to manually change hard coded enum values in the Java code.
=> Dynamic hash codes hmac

jni/jni_hmac.c
Removed redefine of WC_INLINE if using FIPS. This was defined in wolfssl proper.
=> Removed redefine of WC_INLINE if using FIPS.

README.md, README_JCE.md, build.xml, jni/include/com_wolfssl_wolfcrypt_Ecc.h, jni/jni_ecc.c, src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyAgreement.java, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMac.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestMd5.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha256.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha384.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha512.java, src/main/java/com/wolfssl/provider/jce/WolfCryptRandom.java, src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java, src/main/java/com/wolfssl/wolfcrypt/Ecc.java, src/main/java/com/wolfssl/wolfcrypt/NativeStruct.java
This PR includes fixes and cleanup:
- Uses nativeheaderdir in build.xml on supported platforms, otherwise falls back to javah (allows wolfcrypt-jni to compile on newer JDK versions)
- Switches JUnit to use hamcrest-all-1.3.jar, consistent with wolfssljni
- Adds call to wc_ecc_set_rng() to work with recent wolfSSL releases
- README updates
This has been tested against wolfSSL, FIPSv1, FIPSv2, and FIPS Ready on Linux and OS X.
=> nativeheaderdir, wc_ecc_set_rng, cleanup

README.md, jni/jni_ecc.c
This PR preps for the 1.6.0 release and includes:
- README update for version and release date
- Minor warning fix in jni/jni_ecc.c
=> 1.1.0 release prep

src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestMd5.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha256.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha384.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha512.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestMd5Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha256Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha384Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha512Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestShaTest.java, src/test/java/com/wolfssl/wolfcrypt/test/fips/Des3FipsTest.java
This PR adds methods to wolfJCE's `WolfCryptMessageDigestXXX` classes to override the `MessageDigestSpi.engineGetDigestLength()` API.
=> add support for MessageDigestSpi.engineGetDigestLength()

makefile.macosx, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR fixes a JCE test case failure, which will fix the nightly test as well:
```
Testcase: testRSAECBPKCS1PaddingWithTooBigData took 0.086 sec
expected:<[Rsa Padding error]> but was:<[Bad function argument]>
junit.framework.AssertionFailedError: expected:<[Rsa Padding error]> but was:<[Bad function argument]>
at com.wolfssl.provider.jce.test.WolfCryptCipherTest.testRSAECBPKCS1PaddingWithTooBigData(WolfCryptCipherTest.java:1132)
```
The following commit to wolfSSL proper added a new BAD_FUNC_ARG return code that changed the string description of the exception returned at this point in the WolfCryptCipherTest case.  Specific code addition is around the message `Expected that inLen be no longer RSA key length`.
https://github.com/wolfSSL/wolfssl/commit/e9187f5f00
This PR change loosens …
=> Resolve WolfCryptCipherTest failure, fix OSX build

README.md, build.xml, src/main/java/com/wolfssl/wolfcrypt/Asn.java, src/main/java/com/wolfssl/wolfcrypt/BlockCipher.java, src/main/java/com/wolfssl/wolfcrypt/FeatureDetect.java, src/main/java/com/wolfssl/wolfcrypt/Fips.java, src/main/java/com/wolfssl/wolfcrypt/Logging.java, src/main/java/com/wolfssl/wolfcrypt/MessageDigest.java, src/main/java/com/wolfssl/wolfcrypt/Rng.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java
This PR preps for the 1.3.0 release and includes:
- Fixes Javadoc warnings and missing default constructors that show up in newer Java versions
- Fixes deprecation warning for Integer(int) in WolfCryptKeyPairGeneratorTest.java
- Updates README.md and build.xml for 1.3.0
=> Prep for 1.3.0 release

build.xml, examples/provider/ProviderTest.java, examples/provider/ProviderTest.sh, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java
This PR:
- Adds an initial directory structure for JCE examples and adds support to `build.xml` to build them when either `ant build-jce-debug` or `ant build-jce-release` is used.
- Increments the wolfJCE version number in `WolfCryptProvider.java` to match the recent 1.3 release (oversight during last release).
=> Add initial example framework with one ProviderTest JCE example

jni/jni_fips.c, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMacTest.java
This PR fixes a compatibility issue with native wolfSSL FIPS bundles built with `--enable-engine`, which disables old struct names.  This resolves the issue by using current wc_Md5/wc_Sha/etc struct names instead of old ones (Md5, Sha, etc).
This PR also includes fixes for:
- Skip HMAC-MD5 tests in WolfCryptMacTest for FIPS 140-3 bundles (no MD5 support in HMAC CAST)
- Makes the exception checking in one WolfCryptCipherTest.java more generic. Only check for exception, not specific error string since that can change between versions / math libs / FIPS vs. non-FIPS.
=> Use wc_* names for Md5 and Sha structs in jni_fips.c

README_JCE.md, src/main/java/com/wolfssl/wolfcrypt/Fips.java
We had a few non-ASCII apostrophes in Fips.java which were causing a build error on a customer platform.
=> Replace non-ASCII apostrophes in Fips.java/README_JCE.md

jni/include/com_wolfssl_wolfcrypt_Chacha.h, jni/include/wolfcrypt_jni_debug.h, jni/jni_chacha.c, jni/jni_ecc.c, jni/jni_native_struct.c, src/main/java/com/wolfssl/wolfcrypt/Chacha.java, src/test/java/com/wolfssl/wolfcrypt/test/ChachaTest.java, src/test/java/com/wolfssl/wolfcrypt/test/WolfCryptTestSuite.java
This PR cleans up the native wolfCrypt ChaCha wrapper.  It fixes one double free issue on the ChaCha pointer, and adds casting to/from `uintptr_t` where necessary when moving between Java `jlong` and native pointer.
=> Cleanup ChaCha native wrapper, fix double free of ChaCha pointer

README.md, build.xml, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java
This PR includes fixes from v1.4 release cycle and version bumps:
- Bumps version in WolfCryptProvider.java to 1.4
- Bumps version in build.xml to 1.4
- Updates README.md with v1.4 ChangeLog info
- Adjusts build.xml to use correct `${env.LD_LIBRARY_PATH}` instead of just `$LD_LIBRARY_PATH`
=> Prep for 1.4.0 Release

src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestShaTest.java
This PR updated wolfJCE to support the "SHA" algorithm string.  Maps to the same functionality as the "SHA-1" algorithm.  The SUN provider offers "SHA", and some applications expect that to be available.
This also adds a simple test to make sure "SHA" is able to be used via MessageDigest.getInstance().
=> Add SHA cipher alias for SHA-1 to wolfJCE

jni/include/com_wolfssl_wolfcrypt_Md5.h, jni/include/com_wolfssl_wolfcrypt_Sha.h, jni/include/com_wolfssl_wolfcrypt_Sha256.h, jni/include/com_wolfssl_wolfcrypt_Sha384.h, jni/include/com_wolfssl_wolfcrypt_Sha512.h, jni/jni_md5.c, jni/jni_sha.c, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestMd5.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha256.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha384.java, src/main/java/com/wolfssl/provider/jce/WolfCryptMessageDigestSha512.java, src/main/java/com/wolfssl/wolfcrypt/Md5.java, src/main/java/com/wolfssl/wolfcrypt/Sha.java, src/main/java/com/wolfssl/wolfcrypt/Sha256.java, src/main/java/com/wolfssl/wolfcrypt/Sha384.java, src/main/java/com/wolfssl/wolfcrypt/Sha512.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestMd5Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha256Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha384Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha512Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestShaTest.java, src/test/java/com/wolfssl/wolfcrypt/test/Md5Test.java, src/test/java/com/wolfssl/wolfcrypt/test/Sha256Test.java, src/test/java/com/wolfssl/wolfcrypt/test/Sha384Test.java, src/test/java/com/wolfssl/wolfcrypt/test/Sha512Test.java, src/test/java/com/wolfssl/wolfcrypt/test/ShaTest.java
This PR adds support for clone() functionality to JCE MessageDigest classes.  To do this, we also wrap the native `wc_ShaCopy()`, etc APIs and add `copy()` support to the `com.wolfssl.wolfcrypt` message digest classes.
`MessageDigest.clone()` is now supported by:
```
com.wolfssl.wolfcrypt.provider.jce.WolfCryptMessageDigestMd5
com.wolfssl.wolfcrypt.provider.jce.WolfCryptMessageDigestSha
com.wolfssl.wolfcrypt.provider.jce.WolfCryptMessageDigestSha256
com.wolfssl.wolfcrypt.provider.jce.WolfCryptMessageDigestSha384
com.wolfssl.wolfcrypt.provider.jce.WolfCryptMessageDigestSha512
```
This PR also:
- Adds tests for both `com.wolfssl.wolfcrypt` and `com.wolfssl.wolfcrypt.provider.jce` levels for added functionality.
- Improves error checking of native Md5 API calls (`jni_md5.c`)
- Adds missing …
=> Add wolfJCE MessageDigest.clone() support

README.md, build.xml, jni/jni_md5.c, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java
This PR preps for v1.5 release:
- Bumps version in WolfCryptProvider.java
- Bumps version in build.xml
- Adds release notes to README.md
- Adds one cast to `uintptr_t` to Md5.java
=> Prep for 1.5 Release

README_JCE.md, examples/provider/ProviderTest.java
This PR adds a test to the `examples/provider/ProviderTest.java` example which prints out the provider for `new SecureRandom()` and `SecureRandom.getInstanceStrong()`.
The provider for `getInstanceStrong()` is controlled in the system `java.security` file by setting the following property:
```
securerandom.strongAlgorithms=HashDRBG:wolfJCE
```
This example can be built and run with:
```
$ cp makefile.linux makefile
$ make
$ ant build-jce-debug
$ ./examples/provider/ProviderTest.sh
```
If wolfJCE has been installed correctly in `java.security` for `getInstanceStrong()`, you will see:
```
What Provider is providing SecureRandom?
--------------------------------
wolfJCE: [Random] initialized new object
new SecureRandom() = wolfJCE version 1.5
wolfJCE: [Random] initialized new object …
```
=> Add SecureRandom test to ProviderTest example

jni/jni_fips.c, src/test/java/com/wolfssl/wolfcrypt/test/fips/Des3FipsTest.java
This PR fixes native preprocessor guards in `jni/jni_fips.c` around `Des3_fips()` APIs. These are only available in 140-2, not 140-3 / v5 bundles.
=> Des3_fips() API not available in wolfCrypt FIPSv5

scripts/infer.sh, src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/main/java/com/wolfssl/wolfcrypt/FeatureDetect.java, src/main/java/com/wolfssl/wolfcrypt/WolfObject.java
This PR adds a simple bash script to run Facebook Infer over Java classes in this project:
```
$ cd wolfcryptjni
$ ./scripts/infer.sh
```
This also fixes reports that showed up on the current codebase.
=> Facebook Infer script and fixes

src/main/java/com/wolfssl/wolfcrypt/Rng.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptRandomTest.java, src/test/java/com/wolfssl/wolfcrypt/test/RngTest.java
This PR adds synchronization to the methods in `com.wolfssl.wolfcrypt.Rng`, fixing issues around concurrent use.
This also adds threaded tests for the higher-level JCE `com.wolfssl.provider.WolfCryptRandom` class.
Related to ZD 15663.
=> Add synchronization to wolfCrypt Rng Class

README_JCE.md, jni/include/com_wolfssl_wolfcrypt_Rsa.h, jni/jni_ecc.c, jni/jni_rsa.c, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/wolfcrypt/Ecc.java, src/main/java/com/wolfssl/wolfcrypt/Rsa.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java, src/test/java/com/wolfssl/wolfcrypt/test/RsaTest.java
This PR primarily adds RSA support for the JCE KeyPairGenerator class.  In addition, it also:
- Expands `com.wolfssl.wolfcrypt.Rsa` to support the KeyPairGenerator addition
- Clean up pass on native RSA and ECC code, better adhere to coding standards
- Fix typos in `com.wolfssl.wolfcrypt.Ecc` class
=> Add JCE KeyPairGenerator support for "RSA"

jni/jni_ecc.c
This PR corrects the order of operations inside `Java_com_wolfssl_wolfcrypt_Ecc_wc_1ecc_1private_1key_1to_1pkcs8()` in `jni/jni_ecc.c` for the wrapper function around `wc_CreatePKCS8Key()`.
Should fix nightly Jenkins FIPS test.
=> Get ECC curve OID before calling wc_CreatePKCS8Key for size

README_JCE.md, jni/jni_aes.c, jni/jni_fips.c, src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/wolfcrypt/BlockCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java, src/test/java/com/wolfssl/wolfcrypt/test/AesTest.java
This PR adds wolfJCE support for:
- `Cipher.AES/CBC/PKCS5Padding` (plus tests)
- `Cipher.RSA` (alias for `RSA/ECB/PKCS1Padding`)
=> JCE: add support for Cipher AES/CBC/PKCS5Padding, RSA

makefile.macosx
This PR standardizes the native JNI shared library on OSX to `.dylib` extension, which matches OSX shared library naming. Some Java versions won't find `libwolfcryptjni.jnilib` if installed unless it is named `libwolfcrypt.dylib` instead.
=> Standardize JNI library name on OSX to .dylib

.gitignore, README.md, pom.xml
This PR updates Maven build support for wolfCrypt JNI/JCE.  This add better support for an alternative build system for users who want to build with Maven rather than ant.  See `README.md` for build instructions.
Note: this PR does not support building the example application with Maven. That functionality may come in a future PR.
=> Update Maven build support

README.md, jni/jni_fips.c
This PR:
- Removes inclusion/use of CyaSSL headers in `jni/jni_fips.c` now that wolfSSL proper has removed CyaSSL headers and source files (https://github.com/wolfSSL/wolfssl/pull/6667).
- Removes build instructions for FIPSv1 from `README.md` since FIPS cert #2425 is historical.
Should fix https://cloud.wolfssl-test.com/jenkins/job/nightly-FIPSv2-wolfcrypt-jni-ant-test-v2/
=> Remove use of CyaSSL Headers and FIPSv1 from README.md

jni/jni_dh.c, jni/jni_ecc.c, jni/jni_wolfobject.c
This PR improves compatibility with wolfCrypt FIPS 140-3:
- Calls `PRIVATE_KEY_LOCK()` and `PRIVATE_KEY_UNLOCK()` for native JNI operations that need key unlocked with FIPS 140-3
- Adds missing CAST call for ECC CDH on library initialization
- Adds feature detection ifdefs to CAST calls
=> Call PRIVATE_KEY_LOCK/UNLOCK and FIPS_CAST_ECC_CDH for 140-3 compatibility

jni/include/com_wolfssl_wolfcrypt_FeatureDetect.h, jni/jni_feature_detect.c, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/wolfcrypt/FeatureDetect.java
This PR adjusts the native wolfSSL feature detection for HMAC availablility:
- Includes check for `NO_HMAC` when checking if native HMAC functionality is available. If not, HMAC algo won't be broadcast as supported for wolfJCE provider.
- For FIPS 140-3, HMAC-MD5 is not available. Account for this when checking for native features.
=> Adjust native HMAC feature detection, account for no HMAC-MD5 in FIPS 140-3

src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestShaTest.java
This PR adds the string "SHA1" as an algorithm alias for "SHA-1".  Customer testing showed this interop issue, although the "SHA1" string does not seem to be an officially-defined [Java Security Algorithm name](https://docs.oracle.com/en/java/javase/17/docs/specs/security/standard-names.html#messagedigest-algorithms).
=> JCE: add "SHA1" alias for MessageDigest SHA-1, for interop with Sun

src/main/java/com/wolfssl/provider/jce/WolfCryptPKIXCertPathValidator.java
This PR makes one fix to wolfJCE's `CertPathValidator` implementation (`WolfCryptPKIXCertPathValidator`). If `PKIXParameters.getSigProvider()` returns null in `engineValidate()`, the `Signature` provider has not been set. If using wolfCrypt FIPS, explicitly set to `wolfJCE` to help maintain FIPS compliance.
If set to a different Signature provider, we throw an exception when used with wolfCrypt FIPS.
=> CertPathValidator: set PKIXParameters Signature provider if null with wolfCrypt FIPS

src/main/java/com/wolfssl/provider/jce/WolfCryptKeyAgreement.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyAgreementTest.java
This PR adjusts wolfJCE's `KeyAgreement` implementation for generating DH shared secrets.
Native wolfCrypt generates and returns DH shared secrets that have any zero bytes stripped off.  This follows RFC 5246 (8.1.2) which instructs to do so.  Other Java KeyAgreement implementations (SunJCE, Bouncy Castle) for DH follow RFC 2631 (2.1.2) which prepends zero bytes if the total secret size is less than the prime length.
This PR adjusts our wolfJCE implementation to match other existing Java implementations, for interop compatibility. 
This fixes a sporadic JUnit failure which looks similar to this:
```
Testcase: testDHKeyAgreementInterop took 0.016 sec
FAILED
array lengths differed, expected.length=63 actual.length=64; arrays first differed at element [0]; expected:<-18> but was:<0> …
```
=> JCE: prepend zero byte to DH shared secret if less than prime length

src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java
This PR adds synchronization to protected methods in `WolfCryptSignature` class.
This fixes a sporadic JUnit failure that looks similar to:
```
Threading error in RSA sign/verify thread test
junit.framework.AssertionFailedError: Threading error in RSA sign/verify thread test
at com.wolfssl.provider.jce.test.WolfCryptSignatureTest.threadRunnerSignVerify(WolfCryptSignatureTest.java:448)
at com.wolfssl.provider.jce.test.WolfCryptSignatureTest.testThreadedWolfSignWolfVerify(WolfCryptSignatureTest.java:462)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) …
```
=> JCE: add synchronization to protected methods in WolfCryptSignature

src/main/java/com/wolfssl/provider/jce/WolfCryptPKIXCertPathValidator.java, src/main/java/com/wolfssl/wolfcrypt/AesGcm.java, src/main/java/com/wolfssl/wolfcrypt/Dh.java, src/main/java/com/wolfssl/wolfcrypt/Ecc.java, src/main/java/com/wolfssl/wolfcrypt/Hmac.java, src/main/java/com/wolfssl/wolfcrypt/NativeStruct.java, src/main/java/com/wolfssl/wolfcrypt/Rsa.java
This PR fixes a few small Javadoc warnings that showed up when tested with newer Java versions (21, 22).
Only includes comment/doc changes, no functional code changes.
=> JNI/JCE: fix Javadoc warnings with newer Java versions

ChangeLog.md, IDE/WIN/README.md, IDE/WIN/wolfcryptjni.vcxproj, IDE/WIN/wolfcryptjni.vcxproj.filters, README.md, build.xml, jni/jni_ecc.c, jni/jni_feature_detect.c, jni/jni_native_struct.c, jni/jni_wolfobject.c, pom.xml, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java, src/main/java/com/wolfssl/wolfcrypt/Ecc.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyAgreementTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptPKIXCertPathValidatorTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptSignatureTest.java, src/test/java/com/wolfssl/wolfcrypt/test/DhTest.java, src/test/java/com/wolfssl/wolfcrypt/test/RsaTest.java
This PR preps for the 1.6 release, and includes the following changes:
- Moves ChangeLog from `README.md` to `ChangeLog.md`, updates with 1.6 notes
- Bumps library version to 1.6 in `build.xml`, `pom.xml`, and `WolfCryptProvider.java`
- Updates Windows Visual Studio project file
- Fixes native JNI feature detection for HMAC-SHA224
- Adds native feature check for `PBKDF2` in `WolfCryptProvider.java` before broadcasting support for `SecretKeyFactory`
- Fixes Facebook Infer warnings about thread safety in `WolfCryptSignature` class
- Make RNG used in Signature class a class variable, so it is only initialized once instead of each sign() operation
- Refactor `Signature` threaded test to use AtomicIntegerArray
- Only runs `CertPathValidator(PKIX)` CRL test if native CRL has been compiled in
- …
=> Prep for 1.6 Release

.github/workflows/main.yml
This PR removes Java 8 testing from Temurin JDK in GitHub Actions. It looks like Java 8 was removed for Mac OSX runners, error `Error: Could not find satisfied version for SemVer '8'.`.
This same change was made to wolfssljni in https://github.com/wolfSSL/wolfssljni/pull/191
=> GitHub Actions: remove Temurin JDK 8

src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java
This PR removes a call to `BigInteger.longValueExact()` since it's not available on some Java variants/versions.  For example this API is not available in Android API versions less than 31.
=> JCE: KeyPairGenerator: remove use of longValueExact()

.github/workflows/main.yml, jni/include/com_wolfssl_wolfcrypt_Rsa.h, jni/jni_rsa.c, src/main/java/com/wolfssl/wolfcrypt/Rsa.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java, src/test/java/com/wolfssl/wolfcrypt/test/RsaTest.java
This PR detects the native `RSA_MIN_SIZE` value for use in JUnit tests. It also adds a static helper variable to `com.wolfssl.wolfcrypt.Rsa` called `RSA_MIN_SIZE` to easily use that value from Java.
This should fix failing Jenkins test: `nightly-wolfcrypt-jni-ant-test-v2`, which started failing after https://github.com/wolfSSL/wolfssl/pull/7923 was merged.
=> JNI/JSSE: detect RSA_MIN_SIZE in tests, add Rsa.RSA_MIN_SIZE helper

examples/certs/systemcerts/system-cacerts-to-wks.sh
This PR sets the path to the Java `keytool` command correctly based on the detected `JAVA_HOME` location.
This should fix the following failing nightly Jenkins test: `nightly-wolfcrypt-jni-ant-test-v2`
=> Set keytool path correctly in system-cacerts-to-wks.sh

ChangeLog.md, IDE/WIN/README.md, IDE/WIN/wolfcryptjni.vcxproj, IDE/WIN/wolfcryptjni.vcxproj.filters, README.md, build.xml, examples/WindowsConfig.bat, examples/certs/systemcerts/system-cacerts-to-wks.sh, jni/jni_ecc.c, jni/jni_fips.c, jni/jni_jce_wolfsslkeystore.c, pom.xml, scripts/infer.sh, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/wolfcrypt/Chacha.java, src/main/java/com/wolfssl/wolfcrypt/Curve25519.java, src/main/java/com/wolfssl/wolfcrypt/Ed25519.java, src/main/java/com/wolfssl/wolfcrypt/WolfCryptError.java, src/test/java/com/wolfssl/provider/jce/test/WolfSSLKeyStoreTest.java
This PR includes prep work for the wolfCrypt JNI/JCE 1.7 release:
- Adds source and test folders to Maven `pom.xml`
- Adjusts `WolfSSLKeyStoreTest.testLoadSystemCAKeyStore()` to skip with Maven or on Windows
- Fix build compatibility with latest FIPS 140-3 native wolfSSL builds
- Fix Facebook Infer warnings related to potential threading issues (OSX)
- Update Windows Visual Studio project file and README
Tested against release cycle items, including:
- wolfSSL master, 5.7.4, FIPSv2, FIPSv5, FIPS Ready
- Java 8, 11, 17, 20, 22, 23
- Facebook Infer (Mac)
- Android Studio IDE project
- Windows Visual Studio build
=> Prep for 1.7 Release

IDE/Android/app/src/main/cpp/CMakeLists.txt
With wolfSSL PR https://github.com/wolfSSL/wolfssl/pull/8262, Android builds that use CMakeLists.txt now need to define `WOLFSSL_CUSTOM_CONFIG` since it is not using `options.h`.
=> Android: define WOLFSSL_CUSTOM_CONFIG in example Android app

README_JCE.md, examples/provider/CryptoBenchmark.java, examples/provider/CryptoBenchmark.sh
Initial outline for wolfJCE Security Cryptography API benchmark app
=> Basic app and script for wolfJSSE benchmark

jni/jni_fips.c
This PR adjusts `jni_fips.c` to call `wc_RunAllCast_fips()` for HAVE_FIPS_VERSION >= 6. v6 has a few more CASTs than previous versions, and calling the RunAllCast function will make sure we run those up front.
NOTE:
- Jenkins PRB tests have been added to this repo for FIPS v2, v5, v6, and Ready
=> JNI/JCE: call wc_RunAllCast_fips() for HAVE_FIPS_VERSION >= 6

examples/provider/CryptoBenchmark.java
Added AES-GCM to benchmark
Modified test sizes
cleaned up output to resemble wolfssl/wolfcrypt/benchmark.c
=> Adds AES-GCM to benchmark

examples/provider/CryptoBenchmark.java, examples/provider/CryptoBenchmark.sh
For this PR the following features have been added:
- DES algorithm compatibility
- Provider version given at the start of the test
- A comparison table at the end of the test
- Small edit to script file to prompt user for removal of BC files if they started the test with them already installed
=> JCE: Implements DES algorithm, results comparison table and provider version information

ChangeLog.md, IDE/Android/app/src/main/cpp/CMakeLists.txt, README.md, README_JCE.md, build.xml, pom.xml, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/wolfcrypt/WolfObject.java
This PR includes prep work for the wolfCrypt JNI/JCE 1.8 release:
- Update ChangeLog with 1.8 release notes
- Update Android Studio CMakeLists.txt with proper build config for latest wolfSSL FIPS Ready
- Update README.md with note about FIPSv5
- Bump version to 1.8
Tested against release cycle items, including:
- wolfSSL master, 5.7.6, FIPSv2, FIPSv5, FIPS Ready
- Java 8, 11, 17, 20, 22, 23
- Facebook Infer (Mac)
- Android Studio IDE project
- Windows Visual Studio build
=> Prep for 1.8 Release

examples/provider/CryptoBenchmark.java
Added RSA key gen for WolfJCE and BC benchmarks.
=> JCE: Implements RSA key gen benchmark

examples/provider/CryptoBenchmark.java
Added HMAC benchmarking support to CryptoBenchmark
=> JCE: Implements HMAC benchmarks with SHA and MD5

examples/provider/CryptoBenchmark.java, examples/provider/CryptoBenchmark.sh
This PR adds PBKDF2 benchmarks for all JCE providers. Sun had a the following missing:
```
PBKDF2WithHmacSHA3-224
PBKDF2WithHmacSHA3-256
PBKDF2WithHmacSHA3-384
PBKDF2WithHmacSHA3-512
```
The bash script had to be changed to increase the code cache in order to avoid the following warning:
` OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.`
=> JCE: Implements PBKDF2 benchmarks

src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR fixes `Cipher(AES/GCM/NoPadding)` behavior for `getOutputSize(int inputLen)` to correctly strip off the tag length from the expected output size when in DECRYPT mode.
Adds JUnit tests to prevent regression.
We should revisit other algos/modes to see if they need similar adjustments. That will be part of follow up PRs if needed.
ZD 19367
=> JCE: fix Cipher.getOutputSize() for AES/GCM/NoPadding in DECRYPT mode

jni/include/com_wolfssl_wolfcrypt_Asn.h, jni/jni_asn.c, src/main/java/com/wolfssl/provider/jce/WolfSSLKeyStore.java, src/main/java/com/wolfssl/wolfcrypt/Asn.java
This PR adjusts the `com.wolfssl.wolfcrypt.Asn` class to dynamically get the algorithm ASN enum values (ex: `RSAk`, `ECDSAk`, etc) instead of using hard-coded values. This is much more flexible in case these values change at the native level.
These hard coded values broke some unit tests after https://github.com/wolfSSL/wolfssl/commit/1e3718ea7b92b04d9d81dbf8e7d6032ca0a904cb was merged into native wolfSSL.
=> Get ASN algorithm enum values dynamically

README_JCE.md, scripts/infer.sh, src/main/java/com/wolfssl/provider/jce/WolfCryptUtil.java, src/main/java/com/wolfssl/provider/jce/WolfSSLKeyStore.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptUtilTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfJCETestSuite.java, src/test/java/com/wolfssl/provider/jce/test/WolfSSLKeyStoreTest.java
This PR adds a JCE-level utility method which can be used to convert existing `JKS`/`PKCS12` KeyStore `InputStream` objects into a `WKS` (WolfSSLKeyStore) type:
```
public static InputStream convertKeyStoreToWKS(InputStream stream, 
char[] oldPassword, char[] newPassword, boolean failOnInsertErrors)
throws IOException, NoSuchProviderException {
```
This can be useful if WKS type KeyStores need to be used for FIPS compliance, but existing JKS/PKCS12 types need to be converted. This helper method itself will call Sun providers for reading the JKS/PKCS12 entries, before storing them back into a WKS KeyStore. Caution should be taken that calling this code can result in calling down to non-FIPS validated cryptography in those cases when using wolfCrypt FIPS underneath wolfJCE.
This PR also …
=> Add utility method to convert JKS/PKCS12 KeyStore streams to WKS type

examples/provider/CryptoBenchmark.java
Added BC, wolfJCE and Sun signature algorithms benchmarks as well as refactored other test to better insert security providers to avoid provider conflicts.
=> Added signature benchmarks

examples/provider/CryptoBenchmark.java
Added Sha3 ciphers to HMAC benchmark via dynamic algorithm search. As well as minor fix to MD test where two Sun results were showing up as negative.
=> Added Sha3 ciphers to HMAC benchmark

examples/provider/CryptoBenchmark.java
Added KeyGen benchmark and some code cleanup.
=> JCE: Implements KeyGenerator benchmark

examples/provider/KeyStoreBenchmark.java, examples/provider/KeyStoreBenchmark.sh
This PR adds a new example app that runs some benchmarks on the `WolfSSLKeyStore` implementation, along with `WKS` and `PKCS12` KeyStore implementations from `SunJCE`.
This app is compiled when the library is compiled, and can be run from the root directory:
```
$ ./examples/provider/KeyStoreBenchmark.sh --help
KeyStore Benchmark Tool
Usage: java KeyStoreBenchmark [options]
Options:
-provider <name>   Use specified provider (default: benchmark all)
-type <type>       Use specified KeyStore type (default: benchmark all)
-iterations <num>  PBKDF2 iteration count for WKS low-iteration test (default: 20000)
-help              Show this help message
Examples:
java KeyStoreBenchmark (benchmark all types)
java KeyStoreBenchmark -provider SunJCE -type JKS
java KeyStoreBenchmark -iterations 10000 …
```
=> KeyStore benchmark example app

.github/workflows/line-length-check.yml
This PR adds a GitHub action that checks to make sure all added lines are <= 80 characters, to match internal coding standards.
- Only checks `./src`, `./examples`, and `./jni` directories
- Prints out all occurrences of long lines found to actions log
Example of a failure run: https://github.com/wolfSSL/wolfcrypt-jni/actions/runs/16231643997/job/45835457598?pr=126
=> Testing: add GitHub action to check all lines are <= 80 characters

jni/include/com_wolfssl_wolfcrypt_Asn.h, jni/jni_asn.c, src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java, src/main/java/com/wolfssl/wolfcrypt/Asn.java, src/test/java/com/wolfssl/wolfcrypt/test/AsnTest.java, src/test/java/com/wolfssl/wolfcrypt/test/WolfCryptTestSuite.java
This PR fixes some hard-coded ASN.1 OID enum values that were previously correct but after native wolfSSL commit [112351667ada10501771194baeb56b494ffa9435.](https://github.com/wolfSSL/wolfssl/commit/112351667ada10501771194baeb56b494ffa9435) have diverged.
We are changing to retrieving them dynamically from JNI here, so we will always get the accurate/current version of the enum independent of how native wolfSSL has been compiled.
=> JNI/JCE: get hash OID sums dynamically and add to `Asn`

.github/workflows/comment-style-check.yml
This PR adds a GitHub action that checks to make sure new code uses multi-line comment style (ie: `/* */`) not single line style (ie: `//`), to match internal coding standards.
Only checks `.java`, `.c`, and `.h` source files changed in a PR.
Example of a failure run: https://github.com/wolfSSL/wolfcrypt-jni/actions/runs/16276508001/job/45956586842?pr=127
=> Testing: add GitHub action to enforce multi-line style comments

.github/workflows/main.yml, .github/workflows/windows-vs.yml, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyGeneratorTest.java
This PR adds a new GitHub action that tests the Windows Visual Studio project file and solution that ships with this repository (`IDE/WIN`). Currently only testing the non-FIPS configuration.
=> Testing: add GitHub action to test Windows Visual Studio (`IDE/WIN`) project

.github/workflows/line-length-check.yml, README_JCE.md, jni/include/com_wolfssl_wolfcrypt_FeatureDetect.h, jni/include/com_wolfssl_wolfcrypt_Rsa.h, jni/jni_asn.c, jni/jni_feature_detect.c, jni/jni_rsa.c, scripts/infer.sh, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/provider/jce/WolfCryptPssParameters.java, src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java, src/main/java/com/wolfssl/wolfcrypt/FeatureDetect.java, src/main/java/com/wolfssl/wolfcrypt/MessageDigest.java, src/main/java/com/wolfssl/wolfcrypt/Rsa.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptMessageDigestSha3Test.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptSignatureTest.java, src/test/java/com/wolfssl/wolfcrypt/test/RsaTest.java
This PR adds RSA-PSS to the `com.wolfcrypt.Rsa` class, and also to the JCE `Signature` class implementation, including:
```
RSASSA-PSS
SHA224withRSA/PSS
SHA256withRSA/PSS
SHA384withRSA/PSS
SHA512withRSA/PSS
```
And aliases to these for compatibility:
```
SHA224withRSAandMGF1 / SHA224WITHRSAANDMGF1
SHA256withRSAandMGF1 / SHA256WITHRSAANDMGF1
SHA384withRSAandMGF1 / SHA384WITHRSAANDMGF1
SHA512withRSAandMGF1 / SHA512WITHRSAANDMGF1
1.2.840.113549.1.1.10 / OID.1.2.840.113549.1.1.10
```
Also included in this PR is:
- An implementation of `AlgorithmParameters`, for the "RSASSA-PSS" algorithm, which is required for RSA-PSS use above.
- An implementation (alias) for "RSASSA-PSS" is also added to `KeyPairGenerator` for application compatibility. This is just mapped to the regular "RSA" algorithm in …
=> Add RSA-PSS support to JNI wrapper and JCE Signature class

src/main/java/com/wolfssl/provider/jce/WolfCryptDebug.java
This PR changes the time source for debug logs from using `java.sql.Timestamp` to using just the base Java `Instant.ofEpochMilli()`. The advantage of this is that Java 9+ users won't have to import the `java.sql` module, and this can also more easily be used when wolfcrypt-jni JCE provider is used on the bootstrap classpath (`-Xbootclasspath/a`).
=> JCE: change debug log timestamp to use Java Instant.ofEpochMilli()

src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR implements `Cipher.engineGetParameters()`, which was not supported in wolfJCE prior to this.
This helps part of the OpenJDK SunJCE test `crypto/Cipher/EmptyFinalBuffer.java` pass.
Unit tests are included to test enabled algorithms/modes.
=> Implement `Cipher.engineGetParameters()` and add unit tests

src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR adjusts the exception type thrown by `Cipher.init()` if an unsupported or incorrect mode is passed in. It was previously `InvalidKeyException`, but should be `InvalidParameterException` to match what consumers will expect.
This fixes the OpenJDK SunJCE test: `crypto/Cipher/TestCipherMode.java`
=> Throw correct InvalidParameterException from Cipher.init() on unsupported mode

src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR fixes the expected output size for Cipher decrypt operations. When doing decrypt, the output size should not be increased with expected padding, since that padding will be stripped off during decryption.
JUnit test added for regression prevention.
This fixes OpenJDK SunJCE test: `crypto/provider/Cipher/AES/Test4513830.java`
=> Fix expected pad size for decrypt operations

README_JCE.md, src/main/java/com/wolfssl/provider/jce/WolfCryptCipher.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptCipherTest.java
This PR enhances input validation for Cipher `update()` and `doFinal()` methods in regards to bounds checking and null checks. It also improves output buffer size validation with more accurate `ShortBufferException` handling for `PKCS5Padding` decrypt operations.
JUnit tests are included here to prevent against regression.
This fixes the OpenJDK SunJCE test: `crypto/provider/Cipher/AES/Test4517355.java` and `crypto/provider/Cipher/AES/TestShortBuffer.java`
=> Improve Cipher input validation, output buffer sizing, and update behavior

README_JCE.md, src/main/java/com/wolfssl/provider/jce/WolfCryptKeyGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyGeneratorTest.java
This PR implements HmacSHA3 variant support in `KeyGenerator`. We already had HmacSHA3 support in the `Mac` class, but not yet in `KeyGenerator`:
```
KeyGenerator:
- HmacSHA3-224
- HmacSHA3-256
- HmacSHA3-384
- HmacSHA3-512
```
JUnit tests are included here for regression.  This fixes the OpenJDK SunJCE test: `crypto/provider/Mac/MacKAT.java`
=> Add JCE support for HmacSHA3 KeyGenerator

src/main/java/com/wolfssl/provider/jce/WolfCryptKeyPairGenerator.java, src/main/java/com/wolfssl/provider/jce/WolfCryptProvider.java, src/main/java/com/wolfssl/provider/jce/WolfCryptPssParameters.java, src/main/java/com/wolfssl/provider/jce/WolfCryptSignature.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptKeyPairGeneratorTest.java, src/test/java/com/wolfssl/provider/jce/test/WolfCryptSignatureTest.java
This PR includes several fixes for RSA-PSS signature verification and key generation issues:
- Fix `WolfCryptSignature.engineVerify()` to correctly pass digest to `rsaPssVerifyWithDigest()` instead of incorrect digest as "full data"
- Add restriction for `RSAPrivateCrtKey` keys in `WolfCryptSignature`, similar to `WolfCryptCipher`, since native wolfCrypt requires CRT parameters for RSA ops.
- Improve `RSASSA-PSS` `KeyPairGenerator` compatibility with system `KeyFactory`
- Fix default SHA-256 salt length in `WolfCryptPSSParameters`
This PR includes JUnit tests to help prevent regression.
These fixes fix several of the OpenJDK SunJCE tests that were failing with wolfJCE running underneath.
=> Fix RSA-PSS signature verification and key generation issues
